export const REGION_LABEL = {
  'SA-TX':  'San Antonio, TX',
  'AUS-TX': 'Austin, TX',
  'DL-TX':  'Dallas – Fort Worth, TX',
  'EP-TX':  'El Paso, TX',
  'HOU-TX': 'Houston, TX',
  'CHI-IL': 'Chicago, IL',
  'DET-MI': 'Detroit, MI',
  'IN-IN':  'Indianapolis, IN',
  'KC-MO':  'Kansas City, MO',
  'LAX-CA': 'Los Angeles, CA',
  'LV-NV':  'Las Vegas, NV',
  'LX-KY':  'Lexington, KY',
  'NSH-TN': 'Nashville, TN',
  'OC-CA':  'Orange County, CA',
  'PHX-AZ': 'Phoenix, AZ',
  'RDU-NC': 'Raleigh, NC',
  'SBC-CA': 'San Bernardino, CA',
  'SD-CA':  'San Diego, CA',
  'SF-CA':  'San Francisco, CA',
  'SJ-CA':  'San Jose, CA',
  'VC-CA':  'Ventura County, CA',
  'ATL-GA': 'Atlanta, GA',
  'MIA-FL': 'Miami, FL',
  'ORL-FL': 'Orlando, FL',
  'DEN-CO': 'Denver, CO',
  'SEA-WA': 'Seattle, WA',
  'PDX-OR': 'Portland, OR',
  'MIN-MN': 'Minneapolis, MN',
  'STL-MO': 'St. Louis, MO',
  'PHL-PA': 'Philadelphia, PA',
  'BAL-MD': 'Baltimore, MD',
  'CLT-NC': 'Charlotte, NC',
  'NO-LA':  'New Orleans, LA',
  'OKC-OK': 'Oklahoma City, OK',
  'TUL-OK': 'Tulsa, OK',
  'ABQ-NM': 'Albuquerque, NM',
  'TUC-AZ': 'Tucson, AZ',
  'FRE-CA': 'Fresno, CA',
  'SAC-CA': 'Sacramento, CA',
  'BKR-CA': 'Bakersfield, CA',
  'NV-VA':  'Northern Virginia, VA',
};

export const STATE_LABEL = {
  TX: 'Texas',        IL: 'Illinois',      MI: 'Michigan',      MO: 'Missouri',
  CA: 'California',   NV: 'Nevada',        KY: 'Kentucky',      TN: 'Tennessee',
  AZ: 'Arizona',      NC: 'North Carolina', IN: 'Indiana',      VA: 'Virginia',
  GA: 'Georgia',      FL: 'Florida',       CO: 'Colorado',      WA: 'Washington',
  OR: 'Oregon',       MN: 'Minnesota',     PA: 'Pennsylvania',  MD: 'Maryland',
  LA: 'Louisiana',    OK: 'Oklahoma',      NM: 'New Mexico',
};

export const getState = (regionId) => regionId?.split('-').pop() || 'Unknown';


export const REGION_COORDS = {
  'SA-TX':  [29.4241, -98.4936],
  'AUS-TX': [30.2672, -97.7431],
  'DL-TX':  [32.7767, -96.7970],
  'EP-TX':  [31.7619, -106.4850],
  'HOU-TX': [29.7604, -95.3698],
  'CHI-IL': [41.8781, -87.6298],
  'DET-MI': [42.3314, -83.0458],
  'IN-IN':  [39.7684, -86.1581],
  'KC-MO':  [39.0997, -94.5786],
  'LAX-CA': [34.0522, -118.2437],
  'LV-NV':  [36.1699, -115.1398],
  'LX-KY':  [38.0406, -84.5037],
  'NSH-TN': [36.1627, -86.7816],
  'OC-CA':  [33.7175, -117.8311],
  'PHX-AZ': [33.4484, -112.0740],
  'RDU-NC': [35.7796, -78.6382],
  'SBC-CA': [34.1083, -117.2898],
  'SD-CA':  [32.7157, -117.1611],
  'SF-CA':  [37.7749, -122.4194],
  'SJ-CA':  [37.3382, -121.8863],
  'VC-CA':  [34.2747, -119.2290],
  'ATL-GA': [33.7490, -84.3880],
  'MIA-FL': [25.7617, -80.1918],
  'ORL-FL': [28.5383, -81.3792],
  'DEN-CO': [39.7392, -104.9903],
  'SEA-WA': [47.6062, -122.3321],
  'PDX-OR': [45.5051, -122.6750],
  'MIN-MN': [44.9778, -93.2650],
  'STL-MO': [38.6270, -90.1994],
  'PHL-PA': [39.9526, -75.1652],
  'BAL-MD': [39.2904, -76.6122],
  'CLT-NC': [35.2271, -80.8431],
  'NO-LA':  [29.9511, -90.0715],
  'OKC-OK': [35.4676, -97.5164],
  'TUL-OK': [36.1540, -95.9928],
  'ABQ-NM': [35.0844, -106.6504],
  'TUC-AZ': [32.2226, -110.9747],
  'FRE-CA': [36.7378, -119.7871],
  'SAC-CA': [38.5816, -121.4944],
  'BKR-CA': [35.3733, -119.0187],
  'NV-VA':  [38.8816, -77.1945],
};

export const REGION_PHOTOS = {
  'SA-TX':  { day: 'San Antonio, TX - Day.jpg',          night: 'San Antonio, TX - Night.jpg' },
  'AUS-TX': { day: 'Austin, TX - Day.jpg',               night: 'Austin, TX - Night.jpg' },
  'DL-TX':  { day: 'Dallas-Fort Worth, TX - Day.jpg',    night: 'Dallas-Fort, TX - Night.jpg' },
  'EP-TX':  { day: 'El Paso, TX - Day.jpg',              night: 'El Paso, TX - Night.jpg' },
  'HOU-TX': { day: 'Houston, Texas - Day.jpg',           night: 'Houston, Texas - Night.jpg' },
  'CHI-IL': { day: 'Chicago, IL - Day.jpg',              night: 'Chicago, IL - Night.jpg' },
  'DET-MI': { day: 'Detroit, MI - Day.jpg',              night: 'Detroit, MI - Night.jpg' },
  'IN-IN':  { day: 'Indianapolis, IN - Day.jpg',         night: 'Indianapolis, IN - Night.jpg' },
  'KC-MO':  { day: 'Kansas City, MO - Day.jpg',          night: 'Kansas City, MO - Night.jpg' },
  'LAX-CA': { day: 'Los Angeles, CA - Day.jpg',          night: 'Los Angeles, CA - Night.jpg' },
  'LV-NV':  { day: 'Las Vegas, NV - Day.jpg',            night: 'Las Vegas, NV - Night.jpg' },
  'LX-KY':  { day: 'Lexington, KY - Day.jpg',            night: 'Lexington, KY - Night.jpg' },
  'NSH-TN': { day: 'Nashville, TN - Day.jpg',            night: 'Nashville, TN - Night.jpg' },
  'OC-CA':  { day: 'Orange County, CA - Day.jpg',        night: 'Orange County, CA - Night.jpg' },
  'PHX-AZ': { day: 'Phoenix, AZ - Day.jpg',              night: 'Phoenix, AZ - Night.jpg' },
  'RDU-NC': { day: 'Raleigh, NC - Day.jpg',              night: 'Raleigh, NC - Night.jpg' },
  'SBC-CA': { day: 'San Bernadino, CA - Day.jpg',        night: 'San Bernadino, CA - Night.jpg' },
  'SD-CA':  { day: 'San Diego, CA - Day.jpg',            night: 'San Diego, CA - Night.jpg' },
  'SF-CA':  { day: 'San Francisco, CA - Day.jpg',        night: 'San Francisco, CA - Night.jpg' },
  'SJ-CA':  { day: 'San Jose, CA - Day.jpg',             night: 'San Jose, CA - Night.jpg' },
  'VC-CA':  { day: 'Ventura County, CA - Day.jpg',       night: 'Ventura County, CA - Night.jpg' },
  'ATL-GA': { day: 'Atlanta, GA - Day.jpg',              night: 'Atlanta, GA - Night.jpg' },
  'MIA-FL': { day: 'Miami, FL - Day.jpg',                night: 'Miami, FL - Night.jpg' },
  'ORL-FL': { day: 'Orlando, FL - Day.jpg',              night: 'Orlando, FL - Night.jpg' },
  'DEN-CO': { day: 'Denver, CO - Day.jpg',               night: 'Denver, CO - Night.jpg' },
  'SEA-WA': { day: 'Seattle, WA - Day.jpg',              night: 'Seattle, WA - Night.jpg' },
  'PDX-OR': { day: 'Portland, OR - Day.jpg',             night: 'Portland, OR - Night.jpg' },
  'MIN-MN': { day: 'Minneapolis, MN - Day.jpg',          night: 'Minneapolis, MN - Night.jpg' },
  'STL-MO': { day: 'St. Louis, MO - Day.jpg',            night: 'St. Louis, MO - Night.jpg' },
  'PHL-PA': { day: 'Philadelphia, PA - Day.jpg',         night: 'Philadelphia, PA - Night.jpg' },
  'BAL-MD': { day: 'Baltimore, MD - Day.jpg',            night: 'Baltimore, MD - Night.jpg' },
  'CLT-NC': { day: 'Charlotte, NC - Day.jpg',            night: 'Charlotte, NC - Night.jpg' },
  'NO-LA':  { day: 'New Orleans, LA - Day.jpg',          night: 'New Orleans, LA - Night.jpg' },
  'OKC-OK': { day: 'Oklahoma City, OK - Day.jpg',        night: 'Oklahoma City, OK - Night.jpg' },
  'TUL-OK': { day: 'Tulsa, OK - Day.jpg',                night: 'Tulsa, OK - Night.jpg' },
  'ABQ-NM': { day: 'Albuquerque, NM - Day.jpg',          night: 'Albuquerque, NM - Night.jpg' },
  'TUC-AZ': { day: 'Tucson, AZ - Day.jpg',               night: 'Tucson, AZ - Night.jpg' },
  'FRE-CA': { day: 'Fresno, CA - Day.jpg',               night: 'Fresno, CA - Night.jpg' },
  'SAC-CA': { day: 'Sacramento, CA - Day.jpg',           night: 'Sacramento, CA - Night.jpg' },
  'BKR-CA': { day: 'Bakersfield, CA - Day.jpg',          night: 'Bakersfield, CA - Night.jpg' },
  'NV-VA':  { day: 'Northern Virginia. VA - Day.jpg',    night: 'Northern Virginia. VA - Night.jpg' },
};
