export const REGION_LABEL = {
  'SA-TX':  'San Antonio, TX',
  'AUS-TX': 'Austin, TX',
  'DL-TX':  'Dallas – Fort Worth, TX',
  'EP-TX':  'El Paso, TX',
  'HOU-TX': 'Houston, TX',
  'CHI-IL': 'Chicago, IL',
  'DET-MI': 'Detroit, MI',
  'IN-IN':  'Indianapolis, IN',
  'KC-MO':  'Kansas City, MO',
  'LAX-CA': 'Los Angeles, CA',
  'LV-NV':  'Las Vegas, NV',
  'LX-KY':  'Lexington, KY',
  'LV-KY':  'Louisville, KY',
  'NSH-TN': 'Nashville, TN',
  'OC-CA':  'Orange County, CA',
  'PHX-AZ': 'Phoenix, AZ',
  'RDU-NC': 'Raleigh, NC',
  'SBC-CA': 'San Bernardino, CA',
  'SD-CA':  'San Diego, CA',
  'SF-CA':  'San Francisco, CA',
  'SJ-CA':  'San Jose, CA',
  'VC-CA':  'Ventura County, CA',
  'ATL-GA': 'Atlanta, GA',
  'MIA-FL': 'Miami, FL',
  'ORL-FL': 'Orlando, FL',
  'DEN-CO': 'Denver, CO',
  'SEA-WA': 'Seattle, WA',
  'PDX-OR': 'Portland, OR',
  'MIN-MN': 'Minneapolis, MN',
  'STL-MO': 'St. Louis, MO',
  'PHL-PA': 'Philadelphia, PA',
  'BAL-MD': 'Baltimore, MD',
  'CLT-NC': 'Charlotte, NC',
  'NO-LA':  'New Orleans, LA',
  'OKC-OK': 'Oklahoma City, OK',
  'TUL-OK': 'Tulsa, OK',
  'ABQ-NM': 'Albuquerque, NM',
  'TUC-AZ': 'Tucson, AZ',
  'FRE-CA': 'Fresno, CA',
  'SAC-CA': 'Sacramento, CA',
  'BKR-CA': 'Bakersfield, CA',
  'NV-VA':  'Northern Virginia, VA',
};

export const STATE_LABEL = {
  TX: 'Texas',        IL: 'Illinois',      MI: 'Michigan',      MO: 'Missouri',
  CA: 'California',   NV: 'Nevada',        KY: 'Kentucky',      TN: 'Tennessee',
  AZ: 'Arizona',      NC: 'North Carolina', IN: 'Indiana',      VA: 'Virginia',
  GA: 'Georgia',      FL: 'Florida',       CO: 'Colorado',      WA: 'Washington',
  OR: 'Oregon',       MN: 'Minnesota',     PA: 'Pennsylvania',  MD: 'Maryland',
  LA: 'Louisiana',    OK: 'Oklahoma',      NM: 'New Mexico',
};

export const getState = (regionId) => regionId?.split('-').pop() || 'Unknown';

export const REGION_PHOTOS = {
  'SA-TX':  { day: 'San Antonio, TX - Day.jpg',          night: 'San Antonio, TX - Night.jpg' },
  'AUS-TX': { day: 'Austin, TX - Day.jpg',               night: 'Austin, TX - Night.jpg' },
  'DL-TX':  { day: 'Dallas-Fort Worth, TX - Day.jpg',    night: 'Dallas-Fort, TX - Night.jpg' },
  'EP-TX':  { day: 'El Paso, TX - Day.jpg',              night: 'El Paso, TX - Night.jpg' },
  'HOU-TX': { day: 'Houston, Texas - Day.jpg',           night: 'Houston, Texas - Night.jpg' },
  'CHI-IL': { day: 'Chicago, IL - Day.jpg',              night: 'Chicago, IL - Night.jpg' },
  'DET-MI': { day: 'Detroit, MI - Day.jpg',              night: 'Detroit, MI - Night.jpg' },
  'IN-IN':  { day: 'Indianapolis, IN - Day.jpg',         night: 'Indianapolis, IN - Night.jpg' },
  'KC-MO':  { day: 'Kansas City, MO - Day.jpg',          night: 'Kansas City, MO - Night.jpg' },
  'LAX-CA': { day: 'Los Angeles, CA - Day.jpg',          night: 'Los Angeles, CA - Night.jpg' },
  'LV-NV':  { day: 'Las Vegas, NV - Day.jpg',            night: 'Las Vegas, NV - Night.jpg' },
  'LX-KY':  { day: 'Lexington, KY - Day.jpg',            night: 'Lexington, KY - Night.jpg' },
  'LV-KY':  { day: 'Louisville, KY - Day.jpg',           night: 'Louisville, KY - Night.jpg' },
  'NSH-TN': { day: 'Nashville, TN - Day.jpg',            night: 'Nashville, TN - Night.jpg' },
  'OC-CA':  { day: 'Orange County, CA - Day.jpg',        night: 'Orange County, CA - Night.jpg' },
  'PHX-AZ': { day: 'Phoenix, AZ - Day.jpg',              night: 'Phoenix, AZ - Night.jpg' },
  'RDU-NC': { day: 'Raleigh, NC - Day.jpg',              night: 'Raleigh, NC - Night.jpg' },
  'SBC-CA': { day: 'San Bernadino, CA - Day.jpg',        night: 'San Bernadino, CA - Night.jpg' },
  'SD-CA':  { day: 'San Diego, CA - Day.jpg',            night: 'San Diego, CA - Night.jpg' },
  'SF-CA':  { day: 'San Francisco, CA - Day.jpg',        night: 'San Francisco, CA - Night.jpg' },
  'SJ-CA':  { day: 'San Jose, CA - Day.jpg',             night: 'San Jose, CA - Night.jpg' },
  'VC-CA':  { day: 'Ventura County, CA - Day.jpg',       night: 'Ventura County, CA - Night.jpg' },
  'ATL-GA': { day: 'Atlanta, GA - Day.jpg',              night: 'Atlanta, GA - Night.jpg' },
  'MIA-FL': { day: 'Miami, FL - Day.jpg',                night: 'Miami, FL - Night.jpg' },
  'ORL-FL': { day: 'Orlando, FL - Day.jpg',              night: 'Orlando, FL - Night.jpg' },
  'DEN-CO': { day: 'Denver, CO - Day.jpg',               night: 'Denver, CO - Night.jpg' },
  'SEA-WA': { day: 'Seattle, WA - Day.jpg',              night: 'Seattle, WA - Night.jpg' },
  'PDX-OR': { day: 'Portland, OR - Day.jpg',             night: 'Portland, OR - Night.jpg' },
  'MIN-MN': { day: 'Minneapolis, MN - Day.jpg',          night: 'Minneapolis, MN - Night.jpg' },
  'STL-MO': { day: 'St. Louis, MO - Day.jpg',            night: 'St. Louis, MO - Night.jpg' },
  'PHL-PA': { day: 'Philadelphia, PA - Day.jpg',         night: 'Philadelphia, PA - Night.jpg' },
  'BAL-MD': { day: 'Baltimore, MD - Day.jpg',            night: 'Baltimore, MD - Night.jpg' },
  'CLT-NC': { day: 'Charlotte, NC - Day.jpg',            night: 'Charlotte, NC - Night.jpg' },
  'NO-LA':  { day: 'New Orleans, LA - Day.jpg',          night: 'New Orleans, LA - Night.jpg' },
  'OKC-OK': { day: 'Oklahoma City, OK - Day.jpg',        night: 'Oklahoma City, OK - Night.jpg' },
  'TUL-OK': { day: 'Tulsa, OK - Day.jpg',                night: 'Tulsa, OK - Night.jpg' },
  'ABQ-NM': { day: 'Albuquerque, NM - Day.jpg',          night: 'Albuquerque, NM - Night.jpg' },
  'TUC-AZ': { day: 'Tucson, AZ - Day.jpg',               night: 'Tucson, AZ - Night.jpg' },
  'FRE-CA': { day: 'Fresno, CA - Day.jpg',               night: 'Fresno, CA - Night.jpg' },
  'SAC-CA': { day: 'Sacramento, CA - Day.jpg',           night: 'Sacramento, CA - Night.jpg' },
  'BKR-CA': { day: 'Bakersfield, CA - Day.jpg',          night: 'Bakersfield, CA - Night.jpg' },
  'NV-VA':  { day: 'Northern Virginia, VA - Day.jpg',    night: 'Northern Virginia, VA - Night.jpg' },
};
