export const REGION_LABEL = {
  'SA-TX':  'San Antonio, TX',
  'AUS-TX': 'Austin, TX',
  'DL-TX':  'Dallas – Fort Worth, TX',
  'EP-TX':  'El Paso, TX',
  'HOU-TX': 'Houston, TX',
  'CHI-IL': 'Chicago, IL',
  'DET-MI': 'Detroit, MI',
  'IN-IN':  'Indianapolis, IN',
  'KC-MO':  'Kansas City, MO',
  'LAX-CA': 'Los Angeles, CA',
  'LV-NV':  'Las Vegas, NV',
  'LX-KY':  'Lexington, KY',
  'NSH-TN': 'Nashville, TN',
  'OC-CA':  'Orange County, CA',
  'PHX-AZ': 'Phoenix, AZ',
  'RDU-NC': 'Raleigh, NC',
  'SBC-CA': 'San Bernardino, CA',
  'SD-CA':  'San Diego, CA',
  'SF-CA':  'San Francisco, CA',
  'SJ-CA':  'San Jose, CA',
  'VC-CA':  'Ventura County, CA',
  'ATL-GA': 'Atlanta, GA',
  'MIA-FL': 'Miami, FL',
  'ORL-FL': 'Orlando, FL',
  'DEN-CO': 'Denver, CO',
  'SEA-WA': 'Seattle, WA',
  'PDX-OR': 'Portland, OR',
  'MIN-MN': 'Minneapolis, MN',
  'STL-MO': 'St. Louis, MO',
  'PHL-PA': 'Philadelphia, PA',
  'BAL-MD': 'Baltimore, MD',
  'CLT-NC': 'Charlotte, NC',
  'NO-LA':  'New Orleans, LA',
  'OKC-OK': 'Oklahoma City, OK',
  'TUL-OK': 'Tulsa, OK',
  'ABQ-NM': 'Albuquerque, NM',
  'TUC-AZ': 'Tucson, AZ',
  'FRE-CA': 'Fresno, CA',
  'SAC-CA': 'Sacramento, CA',
  'BKR-CA': 'Bakersfield, CA',
  'NV-VA':  'Northern Virginia, VA',
};

export const STATE_LABEL = {
  TX: 'Texas',        IL: 'Illinois',      MI: 'Michigan',      MO: 'Missouri',
  CA: 'California',   NV: 'Nevada',        KY: 'Kentucky',      TN: 'Tennessee',
  AZ: 'Arizona',      NC: 'North Carolina', IN: 'Indiana',      VA: 'Virginia',
  GA: 'Georgia',      FL: 'Florida',       CO: 'Colorado',      WA: 'Washington',
  OR: 'Oregon',       MN: 'Minnesota',     PA: 'Pennsylvania',  MD: 'Maryland',
  LA: 'Louisiana',    OK: 'Oklahoma',      NM: 'New Mexico',
};

export const getState = (regionId) => regionId?.split('-').pop() || 'Unknown';
